### ISSUE TITLE
- No food and water crates

### ISSUE THREAD

**Issue by STX-Garand** [iamthesux/KingsHorses#11]
- No food and water crates

**Comment by LewisSO** [comment]
Added US Food and Water Crate, as well as International Food and Water Crate. If any changes have to be made because of realism feel free to make them.

**Comment by doddsde** [comment]
Where are the crates at?

**Comment by LewisSO** [comment]
They have been created, Moore needs to add to mission?

**Comment by iamthesux** [comment]
yup. will add on next pass through the 3d mission
