### ISSUE TITLE
- Give SASR optics in boxes and 2x sniper rifles (SVDs)

### ISSUE THREAD

**Issue by STX-Garand** [iamthesux/KingsHorses#16]
- Give SASR optics in boxes and 2x sniper rifles (SVDs)

**Comment by LewisSO** [comment]
Added 2x Sniper rifles (SVDs) to the SASR Weapons and Ammo Crate.

**Comment by LewisSO** [comment]
Half done, Closing Issue to revert to issue #31 by Dodds.
