### ISSUE TITLE
Correct SASR Slots, see comment

### ISSUE THREAD

**Issue by doddsde** [iamthesux/KingsHorses#35]
Deckert slot (DM)
Sowers slot (LMG)
Pursehouse slot (RTO)
Constati slot (medic)

**Comment by LewisSO** [comment]
Would this be for loadouts or slot names?

**Comment by doddsde** [comment]
Loadouts

**Comment by LewisSO** [comment]
Wilco, will get it done.

**Comment by LewisSO** [comment]
Corrected Slots, Added correct Loadouts. Good to Go. If anyone sees any problems with the loadouts or code let me know.
