### ISSUE TITLE
DET 5 crate needs optics and AT

### ISSUE THREAD

**Issue by ClineTso** [iamthesux/KingsHorses#37]

**Comment by LewisSO** [comment]
Added AT to the crate, if anyone else wants or sees any changes that need to be made to said AT feel free to do so. Just added basically the same AT for CDF_Recce. As far as optics im unsure of which optics to put in so if anyone wants to also do that or give me the name of the optics that would be sweet.

**Comment by LewisSO** [comment]
Added Optics.
