### ISSUE TITLE
Switch USMC M240G to RHS M240B to utilize TA648 6x ACOG...Or make ASDG_JR compatible with VTN...

### ISSUE THREAD

**Issue by STX-Garand** [iamthesux/KingsHorses#41]

**Comment by iamthesux** [comment]
why are you the way that you are?

out of everyone, you are the last i would expect to ask for better optics. on the fkng 240 no less.

**Comment by iamthesux** [comment]
https://www.youtube.com/watch?v=Gg-maXEg5K8
