### ISSUE TITLE
Pubbie Commander has tablet, can't use it

### ISSUE THREAD

**Issue by wagenbach** [iamthesux/KingsHorses#47]
I think it's too highspeed, but can understand if it's necessary. Either way, there are no CSE options for the Tablet in the Commander slot for the CDF.

**Comment by LewisSO** [comment]
This is one for Moore. The CSE Tablet requires the Command and Control Module to be placed down in the mission in order for these to work. Easy fix, Ill assign Moore to think one and any of the other issues with the same fix will be reverted to this one to keep it clean. As far as I can see it is not currently placed in the mission.

**Comment by LewisSO** [comment]
Should be fixed by : "respawn marker fix" by Moore. If has not been fixed or requires more work re open.
