### ISSUE TITLE
Pubbies not spawning with helmet or any basic bag/backpack

### ISSUE THREAD

**Issue by iball** [iamthesux/KingsHorses#62]
When a pubbies spawns in and is NATO-geared, after re-spawning to get the right gear there is no helmet nor backpack spawned in.

**Comment by iamthesux** [comment]
Should be fixed.  I noticed the CDF medic slot was bugged and didn't get a helmet.  I'm assuming that was the missing helmet issue.  If you notice it again, note the slot that you are in at the time and report back.
